services:
  auth:
    build: .
    env_file:
      - .env
    container_name: auth
    ports:
      - 8000-8000
    command: "uvicorn main:app --reload --port=8000 --host=0.0.0.0"
  postgres:
    image: postgres:15.2
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    ports:
      - 5433:5432
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6378:6379